### ISSUE TITLE
Datepicker is not implemented yet

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#1]
Datepicker for input fields with dates does not work yet

**Comment by gibsonjc** [comment]
If this can't be implemented right away, as an interim step you could add to the gray default text that appears in the boxes to indicate the format, such as,
Start Date (enter the date as month/day/year, e.g. 1/9/2016)
End Date (enter the date as month/day/year, e.g. 1/16/2016)
or similar.

**Comment by patrickzurek** [comment]
Should be no need to modify the placeholder text, I've implemented this on devel.  After I finish client side validation, I'll push the changes to prod and you can test that it works.

**Comment by patrickzurek** [comment]
This change is on prod now.
