### ISSUE TITLE
updated ub_call_slip_processing_statistics_by_date_range.report

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#110]
universal borrowing >  ub_call_slip_processing_statistics_by_date_range.report

A user reported it was missing a column header, so I updated this report to add the missing info.  Please push the updated version to production ASAP as a Resource Sharing Committee member needs to take screenshots of this report for her slides in advance of their webinar next week.  Thanks!

**Comment by patrickzurek** [comment]
Done.
