### ISSUE TITLE
Circ Stat 1: Circulation By Item Location

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#113]
On 12/1, Chris slightly modified and entered the SQL from the report:

Circulation Stat 1: Circulation By Item Location

Please check it out and see if it is comparable to the MS Access version.

**Comment by dmcmpbll** [comment]
circulation_stat_1_circulation_by_item_location.report seems ready to move from devel to prod.

**Comment by patrickzurek** [comment]
Moved.
