### ISSUE TITLE
Updated notes field for item_status_in_transit_for_ub.report on Devel

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/web-reports#114]
I added the text below to the Notes field for the item_status_in_transit_for_ub.report on Devel as a result of RT 86298:

`For more information, refer to the documentation:  <a href="https://www.carli.illinois.edu/products-services/i-share/circ/secure/InTransitStatuses">How To: Manage Old &quot;In Transit-Discharged&quot; or &quot;In Transit-On Hold&quot; Item Statuses</a>`

It can be moved into Prod (as long as my HTML elements above look accurate).

**Comment by gibsonjc** [comment]
Looks good, ready for prod!

**Comment by patrickzurek** [comment]
Done
