### ISSUE TITLE
Remove "Beta"

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#115]
In Jan. 2017, let's remove the "beta" from the name of the service.  Also from the documentation page and the page on the CARLI website.

**Comment by patrickzurek** [comment]
These changes have been made on devel.  I've emailed Ed about making the changes to CARLI's website.

**Comment by gibsonjc** [comment]
Ed made some website changes but I have others to make before we are ready, so I'm taking ownership of this ticket for now.

**Comment by patrickzurek** [comment]
Can I go ahead and make this change to production today?

edit:  I will also move the other reports that are marked ready for prod.

**Comment by patrickzurek** [comment]
This change has been moved to prod.  Please take a quick gander and see if everything looks ok.

**Comment by dmcmpbll** [comment]
A quick glance at prod looks good to me- no "beta" anywhere I see.

**Comment by patrickzurek** [comment]
Same here, looks ok to me.  I'm closing this.
