### ISSUE TITLE
Circ Policy Definitions - Policies tab 

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/web-reports#116]
I've added the SQL for the Circ Policy Definitions - Policies tab in System Administration > Circulation.

I don't have the currency conversion line correct- it's returning the database code before the amount. I've tried the version of the code in the wiki, and the version found in the Local Circulation Maintenance > Fines and Fees> Fines and Fees query. The Fines and Fees query results also show the database code before the amount.

**Comment by dmcmpbll** [comment]
It the web interface converting the dollar sign to the XXXdb database code?

**Comment by patrickzurek** [comment]
It could be. I'll take a look a look.

Pat


On Jan 12, 2017, at 12:43 PM, dmcmpbll <notifications@github.com<mailto:notifications@github.com>> wrote:


It the web interface converting the dollar sign to the XXXdb database code?

**Comment by dmcmpbll** [comment]
Thanks Pat! Chris S. found the answer in Issue #83. 
We need to put a backslash in front of the dollar sign for it to display as a $.

\$

**Comment by jenhm** [comment]
I've tested this issue and reviewed the results in BEN and UIU. No problems were found, It believe it is ready to move to prod.

**Comment by patrickzurek** [comment]
Moved to prod.
