### ISSUE TITLE
Several Reports Edited.  Need to be checked and moved to Prod again.

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#117]
In several reports that contain currency formatting and contain a "$", it needs to be escaped with a "/".  If it is not, then the $ is interpreted as a schema name that is appended to the output in a numeric/currency field.

The following reports have been changed so that the reference to $ has been escaped:

- Local Circ Maintenance -> Fine and Fee Transactions
- Local Circ Maintenance -> Patron Fines and Fees
- Local Circ Maintenance -> Patron Fines and Fees UB Stub Patrons
- Local Cat Maintenance -> Item Records -> Item Records with Price Not Zero
- Local Cat Maintenance -> Item Records -> Item Records with Price Not Zero and Charged

If these are ok with the small change, then they can be pushed to production.

**Comment by jenhm** [comment]
Local Circ Maintenance --> Fine and Fee Transactions is not providing the same results between Access and Web Reports. For the period of 1/1/2016-1/31/2016 @ BRA I get 7 hits in Access and only 3 in Web Reports. See attached Exports with two tabs.

[finefeetranscompare.xlsx](https://github.com/CARLI/web-reports/files/724702/finefeetranscompare.xlsx)

Similarly, I tested in BEN and I got 10 hits in Access and only 2 in Web Reports.

**Comment by csaundrs** [comment]
I will double-check the Fine and Fee Transactions report.  It looks like I need to make some changes.

**Comment by jenhm** [comment]
Realized I was comparing apples to oranges because I was comparing my results from DEVEL Web reports to PROD Access Reports. Sorry for the (probable) false alarm. Will update once I do it right!

**Comment by jenhm** [comment]
OK, so my comparisons are still accurate: in BEN on Web Reports 2 hits, in Access querying Devel, 10 Hits for the Fine & Fee Transactions.

**Comment by jenhm** [comment]
- Local Circ Maintenance > Fines & Fees (not on the list but I noticed) the price displays like this:

     /BENDB15.00

should display
15.00
or
$15.00

- Local Circ Maintenance > Patron Fines & Fees.
- Local Circ Maintenance -> Patron Fines and Fees UB Stub Patrons price displays like this:
 
     /BENDB5.00	

should display
15.00
or
$15.00

- Local Cat Maintenance -> Item Records -> Item Records with Price Not Zero
- Local Cat Maintenance -> Item Records -> Item Records with Price Not Zero and Charged
     Amounts are not shown at all (actually they aren’t shown in current version either), they are shown in    Access version.

Another column should be added at the right and should display the price of the item as x.xx or $x.xx

**Comment by csaundrs** [comment]
What happened here is that I thought the escape character for the (web-reports) reserved character $ was forward slash /

It's actually a backslash \

I have updated the documentation to reflect this.

**Comment by csaundrs** [comment]
There was a separate issue with "Fine and Fee Transactions".  It should be corrected.  Please re-test.

**Comment by csaundrs** [comment]
All listed reports have been addressed for various issues and are ready to be tested again.

**Comment by jenhm** [comment]
I double checked these results and the prices are now showing appropriately (and showing for the Item Records Price not zero queries). 

I think all five of these are ready to be updated on prod: 
Local Circ Maintenance -> Fine and Fee Transactions
Local Circ Maintenance -> Patron Fines and Fees
Local Circ Maintenance -> Patron Fines and Fees UB Stub Patrons
Local Cat Maintenance -> Item Records -> Item Records with Price Not Zero
Local Cat Maintenance -> Item Records -> Item Records with Price Not Zero and Charged

**Comment by patrickzurek** [comment]
These reports have been moved over.
