### ISSUE TITLE
New Batch of Reports Entered

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#118]
These newly entered reports need to be checked for accuracy on web-reports-devel:

All E-Items On Reserve	=>Ready for QA
All Non-E-Items On Reserve	=>Ready for QA
Ampersands in Titles	=>Ready for QA
Authority Records Created By Operator	 =>Ready for QA
Authority Records Updated By Operator	=>Ready for QA
Bib record 035 $a begins OCoLC but has no digits	=>Ready for QA
Cataloging Operator Last Used Date	=>Ready for QA
Circulation Renewals by Patron Group and Item Type	=>Ready For QA
Circulation Transactions by Patron Statistical Categories	=>Ready for QA
Collection Stat 2: Comprehensive MFHD Count	=>Ready for QA
Fine Rates By Item Type  => Ready for QA
Fine Rates By Item Type With Item Counts   => Ready for QA
Unexpired patrons with hold mail email addresses   => Ready for QA
Unexpired patrons with inactive email addresses    => Ready for QA

If they look good, they are ready to move to production.
Once moved to production, please update the "Posted Date" for each report in:

https://docs.google.com/spreadsheets/d/1_eNyTigMdoJfp94OejzhbdcBhgBjo8IvUogefAKnDhA/edit#gid=414492412

**Comment by jenhm** [comment]
I'm going to start with the QA on this list.

**Comment by jenhm** [comment]
I've finished QA on these queries. Except where noted by a link to the new github issue they are all ready for Prod.

All E-Items On Reserve	=>Ready for Prod
All Non-E-Items On Reserve	=>Ready for Prod
Ampersands in Titles	=>Ready for Prod (issue 120 deemed a non-issue)
Authority Records Created By Operator	=>Ready for Prod
Authority Records Updated By Operator	=>Ready for Prod
Bib record 035 $a begins OCoLC but has no digits	=>Ready for Prod
Cataloging Operator Last Used Date	=> see https://github.com/CARLI/web-reports/issues/121
Circulation Renewals by Patron Group and Item Type	=>Ready For prod
Circulation Transactions by Patron Statistical Categories	=>Ready for prod
Collection Stat 2: Comprehensive MFHD Count	=>Ready for Prod
Fine Rates By Item Type => Ready for Prod
Fine Rates By Item Type With Item Counts => See https://github.com/CARLI/web-reports/issues/122
Unexpired patrons with hold mail email addresses => Ready for Prod
Unexpired patrons with inactive email addresses => See https://github.com/CARLI/web-reports/issues/123

**Comment by gibsonjc** [comment]
Just to be clear, these are the 11 new reports that are Ready for Prod:

1. Reserves > All E-Items On Reserve
2. Reserves > All Non E-Items On Reserve
3. Local Cat Maint. > Bib Records > Titles > Ampersands in Titles
4. Cataloging Activity and Statistics > Authority Records Created By Operator
5. Cataloging Activity and Statistics > Authority Records Updated By Operator
6. Local Cat Maint. > Bib Records > Control Numbers > Bib record 035 $a begins OCoLC but has no digits
7. Local Circ Stats > Other Circ Activity Stats > Circulation Renewals by Patron Group and Item Type
8. Local Circ Stats > Other Circ Activity Stats > Circulation Transactions by Patron Statistical Categories 
9. Description of Library's Collection > Annual Collection Stats Package > Collection Stat 2: Comprehensive MFHD Count 
10. Local Circ Maint. > Fines and Fees > Fine Rates By Item Type 
11. Local Circ Maint. > Patron Addresses > Unexpired patrons with hold mail email addresses

**Comment by patrickzurek** [comment]
Jessica, did you add the full paths to the reports for my convenience or just for the record/other reason(s)?  If it's the former then I appreciate you taking the effort although it's not really necessary.  It's not much trouble for me to locate them using the GNU find command, but thanks though :)

**Comment by patrickzurek** [comment]
11. "Local Circ Maint. > Patron Addresses > Unexpired patrons with hold mail email addresses" had a typo in the Linux system filename.  Changed from  expired_patrons_with_hold_mail_email_addresses.report to unexpired_patrons_with_hold_mail_email_addresses.report using the system's mv command, not git's mv command, because the file was not yet tracked by version control.

The new reports have been made available on production.

**Comment by gibsonjc** [comment]
I added the paths because it helps me with my lists of reports, and because I would like them to be somewhere for the record.  I didn't tell anyone this before, so I did it myself here.  I find it helpful to have the full path because so many of the words are similar in the report names and categories.
