### ISSUE TITLE
Ampersands in Titles - Slow

### ISSUE THREAD

**Issue by jenhm** [CARLI/web-reports#120]
The description of the Ampersands in Titles query indicates it will be slow. However, I wanted to double check it since in UIU it takes 20 minutes (retrieves 72,927 records) and in NIU it takes 3 minutes (21,585 records). I didn't want to "approve" query that might be utilizing more resources, as this is as slow as I've seen.

**Comment by csaundrs** [comment]
Though it can take some time, the query from this report does not have an explain plan that is unnecessarily inefficient.  I would not expect this report to cause a problem in production unless it were run in many parallel threads.


Execution Plan
----------------------------------------------------------
Plan hash value: 1056128594

--------------------------------------------------------------------------------
---------------------------------

| Id  | Operation                | Name                         | Rows  | Bytes
|TempSpc| Cost (%CPU)| Time     |

--------------------------------------------------------------------------------
---------------------------------

|   0 | SELECT STATEMENT         |                              | 11046 |   970K
|       |  7379   (1)| 00:00:01 |

|*  1 |  HASH JOIN               |                              | 11046 |   970K
|       |  7379   (1)| 00:00:01 |

|*  2 |   HASH JOIN              |                              | 11046 |   355K
|       |  4535   (1)| 00:00:01 |

|*  3 |    FILTER                |                              |       |
|       |            |          |

|*  4 |     HASH JOIN RIGHT OUTER|                              | 11046 |   280K
|       |  4414   (1)| 00:00:01 |

|   5 |      VIEW                |                              |  1575 | 20475
|       |   472   (1)| 00:00:01 |

|   6 |       HASH UNIQUE        |                              |  1575 | 55125
|       |   472   (1)| 00:00:01 |

|   7 |        INLIST ITERATOR   |                              |       |
|       |            |          |

|*  8 |         INDEX RANGE SCAN | BIB_INDEX_CODE_NORM_DISP_IDX |  1579 | 55265
|       |   471   (1)| 00:00:01 |

|   9 |      VIEW                |                              | 12621 |   160K
|       |  3942   (1)| 00:00:01 |

|  10 |       HASH UNIQUE        |                              | 12621 |   431K
|   624K|  3942   (1)| 00:00:01 |

|* 11 |        INDEX RANGE SCAN  | BIB_INDEX_CODE_NORM_DISP_IDX | 12931 |   441K
|       |  3820   (1)| 00:00:01 |

|  12 |    INDEX FAST FULL SCAN  | BIB_MASTER_SUPPRESS_BID_IDX  |   259K|  1776K
|       |   120   (1)| 00:00:01 |

|  13 |   TABLE ACCESS FULL      | BIB_TEXT                     |   261K|    14M
|       |  2844   (1)| 00:00:01 |

--------------------------------------------------------------------------------
---------------------------------

**Comment by jenhm** [comment]
Thanks, Chris. I'll Add this to the "OK" list, then.
