### ISSUE TITLE
Fine Rates By Item Type With Item Counts slow on UIU

### ISSUE THREAD

**Issue by jenhm** [CARLI/web-reports#122]
I ran Fine Rates By Item Type With Item Counts on UIU and it took 8-9 minutes to return results. There were 4,868 lines, but I thought I'd have Chris S. double check that there were no potential usage issues.

**Comment by jenhm** [comment]
I am running this via Access Reports and it is VERY slow (still waiting for results after 15 minutes) but should still be sure it won't be problematic.

**Comment by csaundrs** [comment]
In terms of resource consumption and potential performance problems, this query tests out ok.  It should not be a problem to run this in production.   The explain plain and cost were quite reasonable.

**Comment by gibsonjc** [comment]
@jenhm have you completed the QA on this one otherwise?  Do you have more things to check or is it ready for prod?  Thanks!

**Comment by jenhm** [comment]
@gibsonjc  Sorry for the late reply, I thought I responded! Yes, this is ready to go since Chris S. indicated there isn't a problem with resource consumption.

**Comment by gibsonjc** [comment]
Local Circ Maint > Fines and Fees > Fine Rates By Item Type With Item Counts

**Comment by patrickzurek** [comment]
I moved the report to production.  I ran it on both prod and devel servers and checked the running time in the celery log file (I made a note to self to document on the wiki how to check this).  376 seconds on devel, 377s on prod.  Should we mention in the notes that this report may take several minutes so that users don't try to submit it multiple times?

**Comment by gibsonjc** [comment]
Good idea, I added a note, so you can push it to prod again.

**Comment by patrickzurek** [comment]
I pushed the updated report to prod.
