### ISSUE TITLE
Updated Reports ready to be pushed to Prod

### ISSUE THREAD

**Issue by jenhm** [CARLI/web-reports#124]
I neglected to update the output columns in the reports I did QA on, so I've gone ahead and done that now, so the following reports are ready to be re-deployed to prod:

Reserves > All E-Items On Reserve
Reserves > All Non E-Items On Reserve
Local Cat Maint. > Bib Records > Titles > Ampersands in Titles
Cataloging Activity and Statistics > Authority Records Created By Operator
Cataloging Activity and Statistics > Authority Records Updated By Operator
Local Cat Maint. > Bib Records > Control Numbers > Bib record 035 $a begins OCoLC but has no digits
Local Circ Stats > Other Circ Activity Stats > Circulation Renewals by Patron Group and Item Type
Local Circ Stats > Other Circ Activity Stats > Circulation Transactions by Patron Statistical Categories
Description of Library's Collection > Annual Collection Stats Package > Collection Stat 2: Comprehensive MFHD Count
Local Circ Maint. > Fines and Fees > Fine Rates By Item Type
Local Circ Maint. > Patron Addresses > Unexpired patrons with hold mail email addresses

**Comment by patrickzurek** [comment]
I moved 10 of the 11 reports to production.  

Jen, I'm sorry.  I accidentally ran the wrong command on one of the files and I reverted it to its previous version before your last change.   The report/file that got reverted is:

`reports/cataloging_activity_and_statistics/authority_records_created_by_operator.report`

You just made changes to the column header titles, right?   Here's the original titles in the file I accidentally reverted:

columns:
- AUTH_HISTORY.OPERATOR_ID: OPERATOR_ID
- CreateMonth: CreateMonth
- AUTH_HISTORY.ACTION_DATE: ACTION_DATE
- 'ACTION_TYPE.ACTION_TYPE ': ACTION_TYPE
- DISPLAY_HEADING: HEADING
- AUTH_HISTORY.AUTH_ID: AUTH_ID

If you remember what you changed those to, you can simply reply to this issue and I'll take care of re-applying the change to that report.

If you feel more comfortable doing it yourself, simply use the Web-Reports Django admin interface (on devel of course) and open the report for editing here, same as before.

**Comment by patrickzurek** [comment]
I didn't pay close attention before, didn't realize how obvious the conversion is.  Is the following what you changed the titles to?  Maybe the last one, "Auth ID", I'm unsure of.


- Operator ID
- Create Month
- Action Date
- Action Type
- Heading
- Auth ID

**Comment by jenhm** [comment]
Hi Patrick,
The only one that is off is “Auth ID” I changed that to “Authority ID” – if you want to update them that’s fine with me!

Thanks!
Jen

**Comment by patrickzurek** [comment]
I made the change on devel and pushed the report to production.  All the reports in this issue have now been moved to prod.
