### ISSUE TITLE
Change way datetimes are written to csv output to ease import into Excel

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#128]
@dmcmpbll mentioned in #127 that MS Excel does not natively understand the format of the datetime string as written to the csv files by WR.  To make it easier to import csv files into Excel we should change the datetime output to a format more easily ingestible by Excel.

They look like this right now:   _2014-05-30 14:21:26+00:00_

**Comment by gibsonjc** [comment]
Another thing I wrote down in my notes was that you wanted to look at if it is possible to unify the outputs of the web display and the CSV file.  You said they use different output writers and that the  web display one was in Unicode.

**Comment by patrickzurek** [comment]
@gibsonjc I wanted to create a separate issue for it.

@dmcmpbll Please test this on devel.  It should apply to any reports you've already ran.  Of course you'll need to download the csv again :). Or run a new report, doesn't matter.

**Comment by dmcmpbll** [comment]
I tested the ability to format the date with the output of queries:
- Authority Records Updated by Operator 
- Cataloging Operator Last Used Date 
- Fine and Fee Transactions 
- Item Tracking 

Worked great for all four!

**Comment by patrickzurek** [comment]
This was moved to prod yesterday sometime around 5:30.  But apparently I failed to hit submit on my comment in this tab.  

It was a simple change, basically just the addition of strftime formatting parameters.   I restarted Apache after pulling the files.
