### ISSUE TITLE
More Reports that have been Translated

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#133]
These are ready for testing:

1) Local Catalog Maintenance - Bibliographic Records - Subjects - > Bibliographic records with Particular Subject Heading Strings.report

2) Local Circulation Maintenance - Patron Data - > Cannot Delete Patron.report

3) Universal Borrowing -> UB Requests – Service times for my patrons.report

**Comment by gibsonjc** [comment]
These three new reports provide the expected results and are ready to be moved to Production.

**Comment by patrickzurek** [comment]
Done.  They all ran fine.
