### ISSUE TITLE
Call Slip Pull List (Unprocessed Requests in Queue)

### ISSUE THREAD

**Issue by dmcmpbll** [CARLI/web-reports#143]
https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-ub#PullList 

@csaundrs added this query to devel.
I added in a pre-populated prompt for call slip queue.

I've tested it with ISU (all queues), DPU (all queues), and UIU (stacks and oak street) on devel; the results match Access.

One consideration is that if an item has more than one barcode, it will be listed more than once. I think I'm okay with this (I added a note to the query description rather than tweak the SQL. Barcodes already get a little complicated with promoted requests).

I ran through the worklist in the wiki; I think it is ready for prod.

(I added the "ready for testing" label in case someone else wanted to take a look at it before we push it over to prod.)

**Comment by gibsonjc** [comment]
Chris Delis moved this into production today. Closing.
