### ISSUE TITLE
Adjust Find "Error" Item Type Code to include varieties of 'error' and 'review'

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#149]
Via email from Ted:
"I discovered this week that a few libraries have use some different names than “Error,” and at least one library still has a “Review” location. I think we could catch these stragglers by modifying the criteria. Instead of explicitly matching item_type_code = ‘Error’, use 
Item_type_name like ‘%ERROR%” or item_type_name like ‘%REVIEW%’ (with appropriate case matching functions)."

He also plans to update the existing Shared SQL in this same way, so everything should remain consistent.

**Comment by gibsonjc** [comment]
Updated on the Shared SQL page: 
https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-local-cat3#0121d

SELECT ITEM_TYPE.ITEM_TYPE_CODE, ITEM_TYPE.ITEM_TYPE_NAME, 
ITEM.ITEM_ID, LOCATION.LOCATION_NAME, MFHD_MASTER.NORMALIZED_CALL_NO, 
utf8to16([mfhd_master].[DISPLAY_CALL_NO]) AS Display_Call_No, 
ITEM.COPY_NUMBER, MFHD_ITEM.ITEM_ENUM, ITEM.CREATE_DATE
FROM (((ITEM INNER JOIN ITEM_TYPE 
ON ITEM.ITEM_TYPE_ID = ITEM_TYPE.ITEM_TYPE_ID) 
INNER JOIN MFHD_ITEM ON ITEM.ITEM_ID = MFHD_ITEM.ITEM_ID) 
INNER JOIN MFHD_MASTER ON MFHD_ITEM.MFHD_ID = MFHD_MASTER.MFHD_ID) 
INNER JOIN LOCATION ON MFHD_MASTER.LOCATION_ID = LOCATION.LOCATION_ID
WHERE (((UCase([ITEM_TYPE_NAME])) Like "*ERROR*" 
 **Or (UCase([ITEM_TYPE_NAME])) Like "*REVIEW*"))**
ORDER BY LOCATION.LOCATION_NAME, MFHD_MASTER.NORMALIZED_CALL_NO;

@csaundrs could you adjust this existing report 
local_catalog_maintenance/item_records/general/find_error_item_type_code.report 
on DEVEL to add this new "Or REVIEW" criteria and I'll test it out? Thanks!

**Comment by csaundrs** [comment]
I have made the change so that any item_type_name that contains the string REVIEW or ERROR and is case insensitive.

...
( UPPER (B.ITEM_TYPE_CODE) LIKE '%%ERROR%%' 
   OR UPPER (B.ITEM_TYPE_CODE) LIKE '%%REVIEW%%')
...

**Comment by gibsonjc** [comment]
Moved to Prod.
