### ISSUE TITLE
 2 Reports Ready for Testing

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#151]
2 new reports ready for testing:

Duplicate OCLC#s Main Query
Item Records with data in the Spine Label field

**Comment by dmcmpbll** [comment]
Jen and I tested these two queries; the results were as expected.
We'll update the descriptive texts, and let you know when to push them to prod!

**Comment by dmcmpbll** [comment]
I think these are ready for prod!

**Comment by gibsonjc** [comment]
Both of these are now on Prod.
