### ISSUE TITLE
Decide about reports list length and age to display

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#17]
There's a configurable option to limit the number of results shown on a the Results list page  which is currently configured to show a max of 25.        It's also currently configured to only show reports not older than 5 days.       Are these reasonable settings?  Do we even want either of them in place?

**Comment by gibsonjc** [comment]
I think that starting with a max list of 25 results and only showing reports from the last five days is a reasonable place to start. At 25, it should fit with only a little scrolling. And the data might change substantially in five days, but this would give users long enough to access "saved" results over a weekend, for example.

It is good to know that there are easily adjustable settings here in case users should let us know that these defaults do not work well for them.
