### ISSUE TITLE
Add a clickable summary menu to the Documentation

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#30]
During user testing, a user said: "For convenience I would prefer menus on the left of the major sections so you can click on the section you want to see and then it would pop out on the right. I do prefer this over scrolling, and, with the menu on the left you get an immediate sense of what's in the documentation."      I am not sure if this exact design is necessary, but a menu can certainly be added at the top with anchors to take the user to each specific section.

**Comment by gibsonjc** [comment]
This page is so short that the scrolling is minimal.  Adding a summary to the top would only make it longer, so I'm not going to change anything at this time.  If the page becomes significantly longer we can revisit its presentation.
