### ISSUE TITLE
Narrow window shows menu icon that does nothing

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#35]
If I shrink my browser window horizontally, eventually a little menu looking box appears in the upper right corner.  It is similar to those I've seen on mobile sites, but when you click on it, nothing happens.
![upper_right_corner_menu_icon](https://cloud.githubusercontent.com/assets/17598357/14330068/5d18d41e-fc04-11e5-9fa6-99fae6dfeb2c.png)

**Comment by patrickzurek** [comment]
I've hidden the "hamburger" icon.  It won't appear when the browser is shrunk or on mobile devices anymore.  However, the site still doesn't function well when small.  What happens is the navbar changes size, hiding the top-most elements of the main content area.  It happens about when the viewable area is less than 768 pixels width.  

How important is it that we get this working for desktop browsers with viewable widths < 768 and mobile devices?

**Comment by gibsonjc** [comment]
I don't think mobile is a big priority right now. If the non-working icon has been removed, then I consider this Issue close-able.
