### ISSUE TITLE
Circ Stat 7 report is broken

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#39]
Local Circulation Maintenance > Annual Circ Statistics Package > Circulation Stat 7: Charges by Circ Happening Loc, Item Type, and Item Loc

It does not run or produce results.  You can open it from the menu but the page is blank.  If you click Submit nothing happens.

When I viewed it in the admin interface I got this error:

AttributeError at /admin/edit/home/pzurek/web-reports/reports/local_circulation_statistics/annual_circulation_statistics_package/circulation_stat_7_charges_by_circ_hap_loc_item_type_and_item_loc.report

'str' object has no attribute 'keys'

**Comment by patrickzurek** [comment]
Looks like this was a report that didn't get converted to the new style way back when so I converted it now.  It runs.  There's still an error in the output however.  Something to do with datatables.  I'm looking into it.

**Comment by patrickzurek** [comment]
This looks like it's outputting correctly now.  Can this be closed?

**Comment by gibsonjc** [comment]
Yes, looks good!
