### ISSUE TITLE
Limit on the number of results output columns

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#40]
We have set a limitation on the number of horizontal columns in the results output so that if it is more than 11, the results must be downloaded by CSV and cannot be viewed in HTML in the site.

@patrickzurek noticed that on reports with a large number of output columns, like 'Fund Transactions - All' which has 23 columns, the table does not fit on the browser page and introduces a horizontal scroll bar.  Content flows beneath the right side bar and  past the top navbar making it look messy.  He made a design decision to not display reports with output columns numbering greater than 11, which is about what will fit inside the page, and instead display the message "This report contains too many columns to display in HTML, please download the CSV file."

**Comment by gibsonjc** [comment]
Additional information and changes on April 1:

Some queries, despite being less than 11 columns, would still instigate a horizontal scroll bar and were flowing beneath the right recent reports side bar.  

Example: Bibliographic or MFHD records with typos at beginning of URL for DPU

We thought about adding an arrow similar to the left side bar to close that.  

@patrickzurek tried adding a CSS style to “break” long words without whitespace but it didn’t help, in this case, a long URL in the output.  

@patrickzurek then made another adjustment so that there’s a horizontal scroll bar within the viewport.  The recent reports column isn't covering this report anymore.

**Comment by patrickzurek** [comment]
I removed the 11 column limit.
