### ISSUE TITLE
HTML markup in Reports text is not working

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#42]
Inputting html into the text of the descriptive fields is currently displaying the mark-up in the text.

Examples: 
Local Cat Maint. > Bib Records > Control Numbers > Bib record 035 $a contains (XXXdb)nnnn 
Local Circ Maint. > Patron Barcodes > Patron Barcode Prefixes That Do Not Belong To Your Library

**Comment by patrickzurek** [comment]
This is working on devel now.
