### ISSUE TITLE
Hide categories with no reports in them from public view

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#44]
Currently every category has a placeholder report "Fund Transactions - All".  We want to remove those before beta testing (except for the one place it belongs legitimately: Acquisitions > Funds and Ledgers).

If possible, please make it so that categories can exist in the File Browser in /admin with no reports in them, but those empty categories will be hidden from the public site.

**Comment by patrickzurek** [comment]
This is done on devel.  I removed all the placeholder reports.  Feel free to test that all the reports on the file system are showing up on the web interface if you'd like but I went through myself and everything looked like it was right.

**Comment by gibsonjc** [comment]
Looks perfect to me on devel!

**Comment by gibsonjc** [comment]
This is in production and looks good.  How does the mechanism work when a new report is added? Will the category just appear automatically?

**Comment by patrickzurek** [comment]
Yes, when a new report is added to a category that was previously hidden, it should now show up automatically.
