### ISSUE TITLE
Change the "Staff Login" checkbox to say "CARLI Staff Login"

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#47]
Since many users will also consider themselves to be "staff" at their own libraries, we should clarify that this is an option for *_CARLI *_staff.

**Comment by patrickzurek** [comment]
This has been changed on devel.

**Comment by gibsonjc** [comment]
Looks great on devel!

**Comment by gibsonjc** [comment]
This is now in production, closing.
