### ISSUE TITLE
Test behavior of logging into web-reports when user has their reporting account password changed

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#49]
Test what will happen when a user has their reporting account password changed.  How will Django respond?  Will it automatically update the record of the user account it has stored internally or will it deny them access to the web-reports site?

**Comment by patrickzurek** [comment]
@csaundrs Chris, on Monday, can we test this by changing DPU_PAT's password and seeing what happens in Django?

**Comment by csaundrs** [comment]
We can test it.  Let me know when you are available and I can do the password change.

**Comment by patrickzurek** [comment]
Oops I forgot that I asked to do this on Monday.  Let's shoot for tomorrow (Tuesday).

**Comment by patrickzurek** [comment]
Nothing unexpected happened.  I was able to log in after my oracle password was changed, and was unable to log in with the old password.
