### ISSUE TITLE
Report "Bibliographic or MFHD records with typos at beginning of URL" results should exclude Authority records

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#50]
Local Catalog Maintenance > Bibliographic Records > General > Bibliographic or MFHD records with typos at beginning of URL

This report returns results for Authority, Bib, and Holdings Records, but it should only return problems in Bib and Holdings records.  Authority records need to be excluded from the results.

Original Access sql and description can be found on the Shared SQL page: https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-local-cat1#urltypo

**Comment by csaundrs** [comment]
Good Catch.  There was a missing condition in the version of the report that was input into the web-reports...

AND A.RECORD_TYPE != 'A'

I have added that and so the query results should reflect it.

**Comment by gibsonjc** [comment]
Great, thanks!  I confirm that this one is now correct on devel.

**Comment by patrickzurek** [comment]
This report was already moved to prod (I can't remember when I did it) so I'm closing this now.
