### ISSUE TITLE
Report "Bibliographic Records Without MFHDs" should include suppressed bibs

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#51]
Local Cataloging Maintenance >  Bibliographic Records > General > Bibliographic Records Without MFHDs

Results from web-reports seem to be omitting bib records that are suppressed (SUPPRESS_IN_OPAC = Y).  Running this query in MS Access includes these suppressed records.

I thought this query was trying to duplicate the basic version,
https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-local-cat1#nomfhd
but you might have been trying to duplicate the libraries-with-Acq version,
https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-local-cat1#nomfhd-yesacq

(I cannot figure out which I may have sent you...or maybe I didn't send it and you selected it some other way.  Not sure!)

**Comment by csaundrs** [comment]
I'm confused on this one.  Looking back, I don't see it in the list you gave me.  Should it be the basic version or the libararies with Acq version?  or do we need them both?

**Comment by gibsonjc** [comment]
I'm confused, too!  I don't know where this one came from because I can't find it in my records either.  It might have been from very early on?  Either way, it is part of the "Suggested Priorities for Bibliographic, Holding, and Item Record Maintenance" that we are targeting.  To be thorough, we should probably provide both versions since some libraries use Acq and some do not.

**Comment by csaundrs** [comment]
I have entered both reports under 

Local Cat Maintenance -> Bibliographic Records -> General ->

Bibliographic Records Without MFHDs
Bibliographic Records Without MFHDs (For libraries that use Acquisistions Client)

If they test out ok, they are ready for production.

**Comment by gibsonjc** [comment]
Great, these both return the same 289 in KNXdb on devel in both Access and Web Reports.

Two reports ready for prod @patrickzurek 

Local Cat Maintenance -> Bibliographic Records -> General ->
1. Bibliographic Records Without MFHDs
2. Bibliographic Records Without MFHDs (For libraries that use Acquisitions Client)

**Comment by patrickzurek** [comment]
Moved.
