### ISSUE TITLE
Report find_holding_and_item_data_for_all_duplicated_barcodes for UIU hangs system

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#53]
The  report local_catalog_maintenance/item_records/barcodes/find_holding_and_item_data_for_all_duplicated_barcodes.report when run for UIU does not complete.  It works for DPU but when run for UIU never finishes.  Attempts to restart celeryd just hang.  I have to reboot the VM to get things running again.

**Comment by csaundrs** [comment]
I tested the SQL for this report in UIU, submitting it directly through sqlplus and it finished in about 1 minute.  I also ran the report in web-reports, and it returned results as well this morning.

Last night, when I ran it it gave me the red text that said something like I would have to wait before I submitted another report.....so I'm not sure what was causing that.

If we see inconsistency with this report in more testing, I will need to watch what is happening when we re-create the hanging scenario.

**Comment by patrickzurek** [comment]
When you ran it in web-reports what school were you logged in as?  UIU?

**Comment by csaundrs** [comment]
This one is actually an Oracle performance issue.  It looks like dynanic sampling is causing the query to run ok the first run.....and then be thrown off by the statistics that are gathered in that run in subsequent runs.  I will investigate what I can do to override this behavior.  The first run takes under or around a minute.....the subsequent runs take much longer...like 30 mins to 45 mins.

**Comment by csaundrs** [comment]
This one has been changed on devel.   It still takes longer on UIU than other schools, but it does return results in a somewhat reasonable amount of time now.  I think if it tests out ok, it is ready for production.

**Comment by gibsonjc** [comment]
This is returning the same results as Access, and it has completed in a reasonable amount of time during my testing for UIC, SIC, and UIU multiple times, though the runs after the first time do take a bit longer.  Go ahead and push to production.

**Comment by patrickzurek** [comment]
Pushed to prod.
