### ISSUE TITLE
Collection Stat 10: Items Lost Missing or Withdrawn appears twice in system

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#55]
This report appears twice.  Under both:

description_of_a_librarys_collection/annual_collection_statistics_package

and

description_of_a_librarys_collection/general

**Comment by gibsonjc** [comment]
This was correct on prod (one in description_of_a_librarys_collection/annual_collection_statistics_package) but still had two on devel. I deleted the extra one on devel in description_of_a_librarys_collection/general
