### ISSUE TITLE
Report FUND TRANSACTIONS - ALL returns server error when downloading CSV file

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#57]
Downloading the CSV file for FUND TRANSACTIONS - ALL under Acquisitions causes a server error to be returned on both prod and devel.

**Comment by patrickzurek** [comment]
Easily fixed.  Change pushed to production.  Can someone take a brief look at the output of Fund Transactions - All and see if the data looks right?

**Comment by gibsonjc** [comment]
I checked a few for this report and the CSV outputs look right to me.

**Comment by gibsonjc** [comment]
This server error for results of Fund Transactions- All still occurs on production.  Should this issue stay open until it is fixed on prod?  (I checked on devel because I couldn't run reports on prod yesterday, and it was corrected on devel.)

**Comment by patrickzurek** [comment]
That's weird. I double checked on prod and the fix is in place.  There must be some other data that's causing it to fail now.  I'll look into it.

**Comment by patrickzurek** [comment]
Can you run the report on devel with the same parameters you ran on prod and take a screenshot of the debug output that should show up on your web browser's screen and send it to me in email?

**Comment by patrickzurek** [comment]
Just the top first page should suffice, thanks.

**Comment by gibsonjc** [comment]
On production I ran in in KNXdb with ﻿﻿
FISCAL PERIOD: 2015-2016
LEDGER NAME: 2015-2016 Reg Ledger

And in EIUdb with
FISCAL PERIOD: FY16
LEDGER NAME: FY16

Both give Server Error (500) when I click on CSV

**Comment by patrickzurek** [comment]
Apache was restarted on prod and the change that was moved from devel to prod should now be in effect and working on prod.
