### ISSUE TITLE
Report "Collection Stat 6: Comprehensive Bib Record Count" missing Unknown format counts and codes

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#58]
The counts and formats that are currently displaying are correct, but the various Unknown formats are missing from the output.  Also, the output should include the two letter format codes (like ac, pm, bc, etc.) in the Bib Format column like the Access output does so that users can easily distinguish between different Unknowns.

Original SQL: https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-desc#12-19d

Results from KNXdb on 4/27/2016 on production follow.

Output from Access:
BibFormat   CountOfBIB_ID
ac=Unknown format   1
pm=Unknown format   1
pc=Mixed Material   1
ca=Unknown format   1
es=Unknown format   1
ic=Unknown format   1
ja=Unknown format   1
ga=Unknown format   2
fm=Unknown format   2
km=Artwork / Chart  2
om=Unknown format   3
ms=Unknown format   3
ad=Unknown format   4
ai=Unknown format   11
ea=Cartographic Mat.    13
hm=Unknown format   30
aa=Unknown format   31
bc=Unknown format   40
mm=Software/Cmptr File  53
bm=Unknown format   53
rm=3D Object    64
tm=Manuscript   71
im=Spoken Word Rec. 246
em=Map, Atlas or Globe  320
cm=Music Score  1857
as=Journal / Magazine   6380
jm=Music Recording  6428
gm=Film / Video 8061
am=Book 222264

Output from Web-Reports production:
Bib Format  Count of bibs
Mixed Material  1
Artwork / Chart 2
Cartographic Mat.   13
Software/Cmptr File 53
3D Object   64
Manuscript  71
Spoken Word Rec.    246
Map, Atlas or Globe 320
Music Score 1857
Journal / Magazine  6380
Music Recording 6428
Film / Video    8061
Book    222264

**Comment by csaundrs** [comment]
I have fixed this one so that it displays like the old MS Access report.  Please double-check.  If it looks good, we can move it to production.

**Comment by gibsonjc** [comment]
Matches Access output now, move to Prod!

**Comment by patrickzurek** [comment]
This was pushed to prod.
