### ISSUE TITLE
Report "Bib record 035 $a contains (XXXdb)nnnn" includes results it should not

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#60]
The only results that this report should return are those where the 035 $a contains something of the form (ABCdb)123456

When I ran this for KNXdb, web-reports returned lines with (Credo) as well:
0350    234076  (Credo)hmdbacl2007  N   Dec. 16, 2011, 05:31 PM
0350    249121  (Credo)prdb2013 N   Aug. 28, 2014, 05:40 PM

Original SQL: https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-local-cat1#071015

**Comment by gibsonjc** [comment]
I should clarify that it does include everything it should, it just has these extra results we do not want.

**Comment by csaundrs** [comment]
I changed the query on Devel so that the string also has to be surrounded by open and close parenthesis.

This should be ready for production.

**Comment by gibsonjc** [comment]
"Bib record 035 $a contains (XXXdb)nnnn" looks good, ready for prod.

**Comment by patrickzurek** [comment]
Hmmm, that's weird.  On devel the file doesn't show up as being changed.  I checked prod and it's there already.  I'm really not sure how that one snuck by onto prod from devel before it was ready...

Maybe I made a typo when adding files to commit and accidentally added that one.  Anyway, it's on prod now!
