### ISSUE TITLE
Report "Titles within a call number range at a specific location" change default text in dropdown

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#61]
Where it says "Location Code" at the top of the list it should say "Location Name"

(Description of a Library's Collection > General)

**Comment by patrickzurek** [comment]
Change made and ready to be pushed to production.

**Comment by gibsonjc** [comment]
Hmm, I don't see a change on devel (or prod, not that I'd expect to).  It still says Code for me.

**Comment by patrickzurek** [comment]
Oh sorry, I made the change in the wrong place.  I changed the title of the column in the output from Location Code -> Location Name.  I fixed it and moved it to prod.
