### ISSUE TITLE
Report "Fines and Fees" not returning complete results

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#63]
(Local Circulation Maintenance > Fines and Fees)

Running this report in Access on KNXdb from 1/1/2016 to 1/15/2016 results in 47 lines.
Running this report in web-reports on KNXdb from 1/1/2016 to 1/15/2016 results in 1 line (which does appear on the Access version, this is just missing the 46 others!).

Original SQL: https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-local-man#fandf

Also, the name needs to be changed to "Fines and Fees", instead of "Fine and Fees" (plural instead of singular fine).

**Comment by csaundrs** [comment]
I have modified this one on devel and it looks like it's getting the expected results.  Please double check and send to production if it's ok.

**Comment by gibsonjc** [comment]
Yes, this one is giving the same results as in Access now.

However, @patrickzurek I get this datatables error before I can see the results.  I checked for empty columns but there aren't any, and I double-checked that all the column names match the SQL.  
![screen shot 2016-06-29 at 10 34 41 am](https://cloud.githubusercontent.com/assets/17598357/16458804/1972deac-3de6-11e6-80dd-f867e99e21fe.png)

**Comment by patrickzurek** [comment]
The problem was START_DATE and END_DATE were listed as columns.  But in the SQL, they weren't being "selected" for.  So I removed those two columns and the report output loads fine now. 

Datatables was expecting output in the report to match those column names and it wasn't finding it.  Ok to move to production?

**Comment by gibsonjc** [comment]
Thanks.  "column not selected for" now on checklist for datatables errors.  :)  Yes, ready for production.

**Comment by patrickzurek** [comment]
Moved to prod.
