### ISSUE TITLE
Report "Item Status “In Transit” for UB" returns zero results

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#64]
In Access for KNXdb today, this query gave 83 results.
In web-reports for KNXdb today, this query gave 0 results.

Original SQL: https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-ub#0927

Universal Borrowing category

**Comment by csaundrs** [comment]
When I test with the version that's currently in devel.....it returns 4393 results for KNX.  The query does not appear to be timeframe dependent, so it would ideally return that many rows for MS Access version as well.  Can you re-test and let me know what you get?

**Comment by gibsonjc** [comment]
I'm not sure you're running the same report...4393 seems like way too many results.  Or was this comment meant to be on a different Issue/report?

This morning on web-reports-devel for KNXdb, Item Status “In Transit” for UB returns zero results:
Download    Title   Parameters  Row Count   Created     ID
CSV     Item Status “In Transit” for UB     None    0   Jun. 20, 2016, 08:35 AM     556bb66c

This morning in MSAccess against oracle-devel in KNXdb, Item Status “In Transit” for UB returns 68 results.

**Comment by csaundrs** [comment]
I changed the ITEM_STATUS Like '%%9%%' or ITEM_STATUS Like '%%10%%'  to
ITEM_STATUS = '9' or ITEM_STATUS = '10'......

I think that was the issue....

The results are now 76 rows in test.

**Comment by gibsonjc** [comment]
Now getting the same 68 results on web-reports-devel just like in Access, so I think this is fixed.  Ready for Prod!

**Comment by patrickzurek** [comment]
It's on production now.
