### ISSUE TITLE
Test wildcard for results on a report

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#65]
May have to do some juggling in the code to get wildcards to be supported since Chris said that they need to be surrounded by quotation marks for Oracle.

**Comment by patrickzurek** [comment]
Chris,
This is a shot in the dark but maybe you can help me out here.  Based on this S.O. question: http://stackoverflow.com/questions/16392288/databaseerror-ora-01036-illegal-variable-name-number I found out what was causing the problems after the switch to using bind statements two weeks ago.

In the question, the answer says: 

> There are a few places where you are attempting to build LIKE clauses by concatenating bind variable placeholders. This concatenation can still be done, but it must be done in SQL using the || operator instead. So, instead of writing ':workarea%', write :workarea || '%', and insted of writing ':jobno_:qcActivity%', write :jobno || '_' || :qcActivity || '%'.

However, I was only able to get that to work if I used **TWO** percent signs back to back.  So using the example given above what I am doing looks like: `:jobno || '_' || :qcActivity || '%%'`

Here's a real example from local_circulation_maintenance/patron_barcodes/patron_barcode_prefixes_that_do_not_belong_to_your_library.report:

`WHERE ( ( (PATRON_BARCODE.PATRON_BARCODE) NOT LIKE '%%' || $BARCODE_PREFIX$ || '%%'`

I could only get that to work when I used two %s, not one.  Oracle returns an error if I try to use one.  

Any idea why?  I'm trying to figure out how to get wildcards working for this query and I'm wondering if it's related to this discrepancy.  Note that in the queries I'm testing, I'm **NOT** using any %'s as input.  I'm entering straight up date.  In DPU's case, it's 20511 for the barcode prefix and 00014 for the other field.

**Comment by patrickzurek** [comment]
BTW here is the actual sql string I'm submitting to oracle after the parameter substitution we do between the $'s:

`WHERE ( ( (PATRON_BARCODE.PATRON_BARCODE) NOT LIKE '%%' || :BARCODE_PREFIX || '%%'`

:BARCODE_PREFIX is a key in the dictionary I pass to the cursor.execute function as part of the bind variable substitution.

**Comment by csaundrs** [comment]
:BARCODE_PREFIX    will need to be inside single quotes......or with the variable subsitution there will have to have a value that is surrounded by single quotes.

Then it should work just fine.

**Comment by patrickzurek** [comment]
Sorry if I wasn't clear.  The report runs fine with regular input (i.e. when I don't use % as an input parameter).  But to test your method, I just tried putting single quotes around :BARCODE_PREFIX and I got a DatabaseError from cx_Oracle.  

If you look at the question on S.O. you'll notice that the answerer doesn't use quotes around the bind parameter either.  Also, if I remember correctly, all our reports used to have quotes around the parameters originally before we started using prepared statements two weeks ago.  I had to remove them from all the queries to get them to work with bind parameters.

**Comment by patrickzurek** [comment]
Does not work:  `WHERE ( ( (PATRON_BARCODE.PATRON_BARCODE) NOT LIKE '%%' || ':BARCODE_PREFIX' || '%%'`

Works: `WHERE ( ( (PATRON_BARCODE.PATRON_BARCODE) NOT LIKE '%%' || :BARCODE_PREFIX || '%%'

Of course the entire string is surrounded by double quotation marks.

**Comment by patrickzurek** [comment]
Ooops, that middle sentence in my last comment should read:

Works: `WHERE ( ( (PATRON_BARCODE.PATRON_BARCODE) NOT LIKE '%%' || :BARCODE_PREFIX || '%%'`

**Comment by patrickzurek** [comment]
In the debug output logging from cx_oracle we can see that it's almost using the % symbol to 'escape' the first percent symbol.  Here's the string I'm submitting to the cursor.execute method:

`WHERE ( ( (PATRON_BARCODE.PATRON_BARCODE) NOT LIKE '%%' || :BARCODE_PREFIX ||'%%'`

And here is the debug output from cx_oracle:

`DEBUG/Worker-2] (0.291) QUERY = u"...WHERE ( ( (PATRON_BARCODE.PATRON_BARCODE) NOT LIKE '%' || :BARCODE_PREFIX ||'%'...`

I've truncated the rest of the query before and after the ellipses.  Notice that it only has a single % in it.  So it's as if the first % is being used as an escape character for the second % symbol.

Edit: so that we're on the same page, the above is what works and produces the correct output.

**Comment by patrickzurek** [comment]
It looks like wildcard searching using % does (sort of -- see below) work when it is part of a string, either at the beginning, middle or end of it.  So for local_circ_maint -> patron_barcodes -> Patron Barcode Prefixes That Do Not Belong To Your Library, all of the following will return results (if we want to use DPU's first field of 20511 for example): "20%", "%0511", and "20%11"  

If I use the wildcard at the beginning or end of the string 20511 in the barcode prefix field, I get the same results returned as if I had searched for 20511 (11 rows), so far so good.  However, if I use it in the middle like so: "2%1", I get 2 less results than expected (9 rows).

23711000001909  

28198942586819  

These above two rows are missing when I use the wildcard in the middle of the string.  

Jessica and Chris:  Any ideas why?

**Comment by gibsonjc** [comment]
This report _excludes_ barcodes from the results that start with the inputs you give it.  And % means zero or more characters.  So the two barcodes you list are excluded because they match starting with 2%1, but they are present in the other results because they do not match starting with 20% %0511, 20%11, or 20511.

**Comment by patrickzurek** [comment]
I think I understand.  So it's working as intended then?

**Comment by gibsonjc** [comment]
Yes, I believe so.  I don't foresee much use of this report with a wildcard because the barcode prefixes and library-use-ID prefixes are fixed and known so there wouldn't be a need for it.  In my opinion, we don't currently have any reports posted that are good candidates for regular wildcard use.  

Side note:  By setting up predefined drop-downs for things like location and type codes in some of the reports, we benefit the users who now don't have to worry about inputting exact codes, but also eliminate the option to use a wildcard to report on multiple codes at the same time. (For example, all the locations that start with law%, though they can simply run a report multiple times, once for each desired code.  Might be a future enhancement idea to allow for this.)

**Comment by patrickzurek** [comment]
Re: pre-populated inputs limit flexibility of using wildcard

I can see that.  I can cook something up that can get around that.  Perhaps a checkbox or something to disable the pre-populated input and allow for user defined input.  I'll leave it to your discretion or a future meeting to decide where it ranks on the priority scale.

**Comment by gibsonjc** [comment]
Spun off into #82 so now I'll close this one.
