### ISSUE TITLE
Unable to download CSV file for "Titles within a Call number range at a specific location" at KNX

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#66]
Laurie from KNX reported that she was unable to download the CSV file for "Titles within a Call number range at a specific location."  I resolved this by passing the data through the xstr function in result_views.py prior to writing it to the csv file.

**Comment by patrickzurek** [comment]
Accidentally closed this issue.  This fix is in on devel.  Jessica, can I move it to production?

**Comment by gibsonjc** [comment]
Yes, ok to move to production.  I don't get the error on devel now with the same reports/parameters that I still get the error with on prod.

**Comment by patrickzurek** [comment]
Done
