### ISSUE TITLE
Newly Entered Reports

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#67]
These reports were added to web-reports-devel:
(They probably need to pass muster as far as being tested and results verified, but then can be moved to production if they do)

Local Catalog Maintenance -> Item Records -> Barcodes -> Items with no active barcode
Local Catalog Maintenance -> Item Records -> General ->  Item records containing double quote
Universal Borrowing ->  List patrons with materials charged from other I-Share libraries
Universal Borrowing ->  UB Call Slip Processing Statistics by Date Range

**Comment by patrickzurek** [comment]
I was working on some other stuff on the server so likely when you tried to run these Chris they wouldn't have worked.  I restarted Apache and "Items with no active barcode" and "List patrons with materials charged from other I-Share libraries" run.  

There's errors with "Item records containing double quote" and "UB Call Slip Processing Statistics by Date Range."  I'm looking at the SQL to see if I can correct them.

**Comment by patrickzurek** [comment]
I fixed _Item records containing double quote_ by escaping the % symbol with another % symbol like so: `'%%\"%%'`.

_UB Call Slip Processing Statistics by Date Range_ wasn't working because it didn't have a date formatting function in it.  I added `to_date(param,'MM-DD-YYYY')` where it was required.

All four should be working now.  Jessica, can you test that they're returning accurate results?

**Comment by gibsonjc** [comment]
Pat, please push these four to prod at your convenience.  I tested them against Access and got the same results, and cleaned up the text fields.

Local Catalog Maintenance -> Item Records -> Barcodes -> Items with no active barcode
Local Catalog Maintenance -> Item Records -> General -> Item records containing double quote
Universal Borrowing -> List patrons with materials charged from other I-Share libraries
Universal Borrowing -> UB Call Slip Processing Statistics by Date Range

**Comment by patrickzurek** [comment]
These reports are on production now.
