### ISSUE TITLE
add icon to CSV download link on Results page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#71]
Consider adding an icon to CSV download column. A downward arrow is often part or all of a downloadable icon.

**Comment by patrickzurek** [comment]
This is in on devel now.  Please take a look.  Also, as an alternative to showing the icon next to every CSV link another idea is to display it once at the top next to the Download text:

<img width="377" alt="screen shot 2016-06-08 at 8 30 02 am" src="https://cloud.githubusercontent.com/assets/6615138/15895910/446c9ed4-2d53-11e6-8acb-a9d04639426f.png">

**Comment by gibsonjc** [comment]
I think it looks good with the cloud icon next to and part of the CSV link every time (like it is on devel right now).  Make it so on prod!

(If later we should ever add any other download options, it might make more sense then to move it up to the column header.)

**Comment by patrickzurek** [comment]
Pushed to prod.
