### ISSUE TITLE
add to Documentation that Results page auto refreshes

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#72]
Does the screen auto refresh when a report is pending? Yes.  Add this to Documentation page: both the right side bar of "Recently Completed Reports" as well as the main "Results" page automatically refresh themselves every 10 seconds.  So there's no need to manually refresh the page.

**Comment by gibsonjc** [comment]
I edited the documentation page.  @patrickzurek can you push this to prod at your convenience?  Thanks!

**Comment by patrickzurek** [comment]
Pushed to prod.
