### ISSUE TITLE
add link to CSV at top of HTML results pages

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#74]
When you choose to show HTML results of a report on the screen, it would be handy to have the link to the CSV right at the top of the list of results. That would save you the step of having to click on Results in the top menu in order to find and download the CSV. A small thing, but an efficiency nonetheless.

**Comment by patrickzurek** [comment]
This is in on devel.  Let me know how it looks.

**Comment by gibsonjc** [comment]
This look and works great.  Production, ho!

**Comment by patrickzurek** [comment]
Pushed to prod.
