### ISSUE TITLE
suggestions to improve the icon/method that closes the left pane

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#75]
Reports pane: left arrow icon. I wasn’t expecting this icon to close the pane. So I was a little worried at first on how I could get it back (clicking the Reports menu above). Maybe a different icon would be useful, one that didn’t look like the browser’s back button, also some tooltip text (“close pane”). Positioning it at an edge might work too. I do like the functionality, and I think it could probably be useful in the Recently Completed (right) pane as well.

**Comment by gibsonjc** [comment]
Find an X icon (instead of a back arrow), and try to move it to the upper right corner.

Collapses to a tab?

Maybe apply to Recently Completed Reports as well.

**Comment by patrickzurek** [comment]
For the left/reports sidebar, I changed the icon and positioned it in the top right.  How does it look?

**Comment by gibsonjc** [comment]
The x in the right corner looks good to me and works as I'd expect. It can be moved to production to replace the back arrow.

Did you have any luck with getting the sidebar area to collapse to a tab or similar so that someone could click on it over there and get it to pop back out?  Or any thoughts on providing the same close functionality to the Recent Reports area on the other side?  Should those ideas two be spun off into separate Issues?

**Comment by patrickzurek** [comment]
I haven't researched collapsing the sidebars.  Since the "X" is ready to go into prod I think the tabs idea should be spun off into it's own issue.

**Comment by patrickzurek** [comment]
The "X" change has been pushed to prod but leaving this open in case there's more discussion about the tabs idea here.

**Comment by patrickzurek** [comment]
I added an option to the right side navbar drop down menu to toggle the Recently Completed Reports pane on and off.  A cookie has been configured to record the user's preference.  It defaults to on for all users.  I've pushed the change to production.
