### ISSUE TITLE
Results vs. Recently Completed Reports vs. report output

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#77]
The documentation page identifies that the Results page has a CSV link in an Output column. However, I inferred that the “Results” page was the actual report output screen; thus I worried that I couldn’t see the link on that page. The use of “Result” in the recently completed pane seems to reinforce the idea that the report output is the results page. Then I clicked on the Results link at the top, and found the list of report outputs. That said, the report output is A result; the results screen shows each query’s result. However, the output from a query or search is commonly pluralized to “results.”

**Comment by gibsonjc** [comment]
Let's try changing the text in the top menu from "Results" to "View All Results" to try to clear things up.
(Note to self @gibsonjc : need to update the Documentation page to match.)

I think the improvements made on #76 to the Recently Completed pane will also help with confusion about the multiple uses of the word "result(s)".

**Comment by patrickzurek** [comment]
Just to be clear, you're talking about the very top navbar, next to the Reports drop down menu, right?

**Comment by gibsonjc** [comment]
Yes, that's right.  The top, purple nav bar to the right of the word "Reports".

**Comment by patrickzurek** [comment]
It's been changed on devel but not pushed to prod.

**Comment by gibsonjc** [comment]
This looks good, let's move it to prod and see if it helps.

**Comment by patrickzurek** [comment]
Pushed to prod.
