### ISSUE TITLE
timer for pending reports?

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#79]
Could you add a timer for pending results saying “estimated x minutes to finish…” I realize that may be too complex to add given the variety of sizes of bib dbs and query steps.

**Comment by gibsonjc** [comment]
@patrickzurek commented elsewhere: 
I don't think that's data we could pull from the back end.  Maybe @csaundrs knows of a way in Oracle to estimate a query's expected run time, but I'm not aware of anything that I've programmed with that allows me to see that.

**Comment by csaundrs** [comment]
It's pretty difficult to predict a run-time.  Plus the criteria that a user provides or database usage could make things take longer.  I think the best we can do is on some reports say that "This one will take a while"  or..."this one takes around 15 mins to complete"....
