### ISSUE TITLE
No query design view to see what is included in the report

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#80]
I became used to adapting existing reports to what was specifically needed or writing new reports. The web-based service is nice but I can't look at the query design to see what specifically is included in the report

**Comment by csaundrs** [comment]
Isn't this request covered in the "Displayed SQL" section
?

**Comment by gibsonjc** [comment]
There is a section for this information in the report file but we didn't implement its display in the redesign.  If we hear from more users that they'd like to see the SQL, we can consider re-enabling this information in display.
