### ISSUE TITLE
Report "Bibs Without Indexed Titles" output does not match Access output

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#85]
On 6/15/2016 in KNXdb on devel, Access returns three results:
BIB_ID  LeaderByte9
220386  a
249017  a
255330  a

Web-reports-devel returns zero results.

local_cat_maint=> bib_records=>titles=>bibs_without_indexed_titles.report
Original: https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-local-cat1#070622a

**Comment by csaundrs** [comment]
I have re-configured this report on the devel environment so that it gets the correct results.  If it looks good to you, I think it is ready to move to prod.

**Comment by gibsonjc** [comment]
Yes, these results match Access now. Ready for Prod.

**Comment by patrickzurek** [comment]
I pushed it to prod.  The column headings are BIB_ID and LeaderByte9.  Did you want me to edit that to something more descriptive like "Bibliographic ID"?

**Comment by gibsonjc** [comment]
Column headings are ok as is for now.
