### ISSUE TITLE
Push updated reports files to Prod

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#86]
I updated the notes fields on the following three reports on web-reports-devel.  Please push the changed files to Production:
1. Local Circ Maint > Fines & Fees > Fine and Fee Transactions
2. Local Circ Maint > Patron Purge and Expiration Dates > Expired Patron Records
3. Local Circ Statistics > Other Circ Activity Statitics > Circulation Transactions by Patron Group and Item Type

**Comment by patrickzurek** [comment]
I've pushed the changes from these reports to prod.
