### ISSUE TITLE
7 new system admin reports ready for testing

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#87]
I have added seven sys admin reports.  All run, but the results will need to be verified.  I converted the ones I could on the sys admin reports page.  Chris will have to take care of the others.

system_administration/circulation/no_fill_reasons_for_callslips.report
system_administration/circulation/circ_happening_locations_default_print_locations.report
system_administration/other/location_limit_group_values.report
system_administration/other/print_locations_global_settings.report
system_administration/item_types/default_call_number_type_and_item_type_per_location_code.report
system_administration/cataloging/cataloging_policy_group_locations_missing_default_item_types.report
system_administration/operators/operators_with_circ_privileges.report

I did my best to put them into the right sub-categories, but some may need to be moved around.

**Comment by gibsonjc** [comment]
To match the subcategories on https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-sysadmin please move:
1.  /system_administration/circulation/no_fill_reasons_for_callslips.report to the /other/ subcategory
2.  /system_administration/item_types/default_call_number_type_and_item_type_per_location_code.report to the /cataloging/ subcategory

Once those two are moved, you can push all 7 to production!

**Comment by patrickzurek** [comment]
I moved the two reports to their new correct directories and pushed the 7 reports to production.  Confirmed on prod that they now show up.
