### ISSUE TITLE
Add three new I-Share libraries to prod and devel

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#88]
Please add BHC, MLS, and SSC to production and devel Web Reports systems.  They are live on Voyager now for all functionality.

**Comment by patrickzurek** [comment]
Three new libraries added and apache restarted.  Changes were made to web-reports/reporting/settings.py separately on both devel and prod since the settings.py file is not tracked by version control.

**Comment by gibsonjc** [comment]
For the record, we also learned that celery needed to be restarted on prod after the school's accounts were added to the login/password file (settings.py).
