### ISSUE TITLE
Can we add "Circulation Stat 5: Comprehensive Circulation by Happening Loc"?

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#91]
Request from DMC to include Circulation Stat 5: Comprehensive Circulation by Happening Loc

https://www.carli.illinois.edu/products-services/i-share/reports/secure/sql-loc-circ#12-09e

(I think this one was already on the initial list of reports and was found to be too complicated for this web format, but I can't find email evidence.  Chris, can you make a ruling on this Issue for the record?  Thanks!)

**Comment by csaundrs** [comment]
Yes, this report uses the MS Access "PIVOT" function which I need to figure out how to emulate in Oracle.

**Comment by dmcmpbll** [comment]
I'll take this one and work from the Annual Stat SQL to convert it over- will update the SQL spreadsheet once I have editing permissions.

**Comment by dmcmpbll** [comment]
I've entered Circ Stat 5 SQL from the Annual Stats, but note upon running it (both in Centos and in Web Reports Devel) that it does not include the mentioned "off-site" category, which the Microsoft Access version contains. Will review.

**Comment by dmcmpbll** [comment]
Have added that category; will double-check query for prod after the new year.

**Comment by dmcmpbll** [comment]
Ran the query for UIU-devel for 1/1/2014-1/1/2015 and the Access results matched the Web Reports results. Have run through the checklist in the CARLI wiki.

I think it is ready to move to prod.

**Comment by dmcmpbll** [comment]
Sorry- hold off on the move to prod- we need to discuss Circ Stat 5 overall.

**Comment by dmcmpbll** [comment]
Following discussion of Circ Stat 5, it is ready to move to prod.

**Comment by patrickzurek** [comment]
Does this mean that we're now able to input reports that use the Access "PIVOT" function?

**Comment by dmcmpbll** [comment]
No, not yet. It means that this version (and the Annual Stats version) produces the data in a long list with a column for transaction type. 

If libraries want to make the results formatting match the PIVOT formatting that Access can do, it takes some manual tweaking.

The counts produced by both reports is the same, it's only the formatting that is different.

**Comment by patrickzurek** [comment]
Report moved to production.
