### ISSUE TITLE
Report "Bib record 035 begins OCoLCocn but less than 9 digits" returns different results

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#92]
These are ready for testing and if ok, a push to production.

-> Local Catalog Maintenance -> Control Numbers -> individual_bibs_with_more_than_one_OCLC_number.report  
-> Local Catalog Maintenance -> Control Numbers -> bib_record_035_lacks_OCoLC_prefix.report  
-> Local Catalog Maintenance -> Control Numbers -> bib_record_035_lacks_ocm_or_ocn_prefix.report  
-> Local Catalog Maintenance -> Control Numbers -> bib_record_035_begins_ocmocm.report  
-> Local Catalog Maintenance -> Control Numbers -> bib_record_035_begins_ocolcocn_but_less_than_9_digits.report  
-> Local Catalog Maintenance -> Control Numbers -> bib_record_035_begins_ocolcocm_but_lacks_leading_zeroes.report  
-> Local Catalog Maintenance -> Control Numbers -> bib_record_035_begins_ocolcocm_but_has_more_than_8_digits.report  
-> Local Catalog Maintenance -> Control Numbers -> bib_record_035_A_has_malformed_ocolc_prefix.report

**Comment by gibsonjc** [comment]
@patrickzurek Can you help?  When I try to view the results in web-reports-devel (for any of these that have more that 0 results) I get this error:
"DataTables warning: table id=d-tables - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

I will download the CSV results to check them against Access.

**Comment by gibsonjc** [comment]
@csaundrs Local Catalog Maintenance -> Control Numbers -> **bib_record_035_begins_ocolcocm_but_lacks_leading_zeroes.report**
seems to be duplicating the SQL of Local Catalog Maintenance -> Control Numbers -> **bib_record_035_begins_ocolcocm_but_has_more_than_8_digits.report**
and giving the same results.

Can you check the **bib_record_035_begins_ocolcocm_but_lacks_leading_zeroes.report** SQL?  Maybe you accidentally copied the wrong SQL here?

**Comment by csaundrs** [comment]
hmm... The SQL for these 2 reports are the same in the last file that was sent.  

## I would assume that the first is the one that is correct because the second doesn't seem to look for leading characters...

OC6.D Bib record 035 $a begins OCoLCocm but has more than 8 digits
Local Cat Maint > Bibliographic Records: Control Numbers

What it does: Finds 035 fields that have the (OCoLC)ocm prefix, but should probably contain the (OCoLC)ocn prefix, due to the number of digits.
This might be useful for: Identifying bibs that can contribute to duplicate records, discards or false overlays in either the local databases or in the I-Share union catalog due to non-standard formatting of the OCLC number.  Records with more than 8 digits in the OCLC number when properly formatted should begin with the (OCoLC)ocn prefix.
Notes: There is a macro on the Shared Macro page called Changebib_035afixocm.mex that can take the results of this query as an input file and correct most of the records with a mismatch between the number of digits in the OCLC number and the (OCoLC)ocm prefix.  It is recommended that the results of this query be spot-checked for obvious errors in the OCLC numbers before running the macro.
Fields in the final report: BIB_ID, TITLE_BRIEF, OCLCNumDigits, DISPLAY_HEADING, NORMAL_HEADING, SUPPRESS_IN_OPAC, CREATE_DATE
<a href="https://www.carli.illinois.edu/products-services/i-share/cat/Cat-maintpriority-OC1-20#OC6">Suggested Priorities for Bibliographic, Holding, and Item Record Maintenance OC6.D</a>

SELECT BIB_INDEX.BIB_ID, BIB_TEXT.TITLE_BRIEF, Len([DISPLAY_HEADING])-10 
AS OCLCNumDigits, BIB_INDEX.DISPLAY_HEADING, BIB_INDEX.NORMAL_HEADING, 
BIB_MASTER.SUPPRESS_IN_OPAC, BIB_MASTER.CREATE_DATE
FROM (BIB_INDEX INNER JOIN BIB_MASTER ON BIB_INDEX.BIB_ID = BIB_MASTER.BIB_ID) 
INNER JOIN BIB_TEXT ON BIB_INDEX.BIB_ID = BIB_TEXT.BIB_ID
WHERE (((BIB_INDEX.DISPLAY_HEADING) Like "(OCoLC)ocm*") AND 
((Len([DISPLAY_HEADING]))>Val(18)) AND ((BIB_INDEX.INDEX_CODE)="0350"))
ORDER BY Len([DISPLAY_HEADING]);

---

OC6.E Bib record 035 $a begins OCoLCocm but lacks leading zeroes
Local Cat Maint > Bibliographic Records: Control Numbers

What it does: Finds 035 fields that have the (OCoLC)ocm prefix, but the number of digits is less than 8, meaning the 035 field lacks leading zeroes.
This might be useful for: Identifying bibs that can contribute to duplicate records, discards or false overlays in either the local databases or in the I-Share union catalog due to non-standard formatting of the OCLC number.  Records with the (OCoLC)ocm prefix when properly formatted should contain a total of 8 digits, including the proper number of leading zeroes for a total of 8 digits.
Notes: There is a macro on the Shared Macro page called Changebib_035afixocm.mex that can take the results of this query as an input file and correct most of the records with a mismatch between the number of digits in the OCLC number and the (OCoLC)ocm prefix, by adding leading zeroes.  It is recommended that the results of this query be spot-checked for obvious errors in the OCLC numbers before running the macro.
Fields in the final report: BIB_ID, TITLE_BRIEF, OCLCNumDigits, DISPLAY_HEADING, NORMAL_HEADING, SUPPRESS_IN_OPAC, CREATE_DATE
<a href="https://www.carli.illinois.edu/products-services/i-share/cat/Cat-maintpriority-OC1-20#OC6">Suggested Priorities for Bibliographic, Holding, and Item Record Maintenance OC6.E</a>

SELECT BIB_INDEX.BIB_ID, BIB_TEXT.TITLE_BRIEF, Len([DISPLAY_HEADING])-10 
AS OCLCNumDigits, BIB_INDEX.DISPLAY_HEADING, BIB_INDEX.NORMAL_HEADING, 
BIB_MASTER.SUPPRESS_IN_OPAC, BIB_MASTER.CREATE_DATE
FROM (BIB_INDEX INNER JOIN BIB_MASTER ON BIB_INDEX.BIB_ID = BIB_MASTER.BIB_ID) 
INNER JOIN BIB_TEXT ON BIB_INDEX.BIB_ID = BIB_TEXT.BIB_ID
WHERE (((BIB_INDEX.DISPLAY_HEADING) Like "(OCoLC)ocm*") AND 
((Len([DISPLAY_HEADING]))<Val(18)) AND ((BIB_INDEX.INDEX_CODE)="0350"))
ORDER BY Len([DISPLAY_HEADING]);

---

**Comment by gibsonjc** [comment]
I fixed the **bib_record_035_begins_ocolcocm_but_lacks_leading_zeroes.report** SQL in the /admin tool.  The difference in these two queries is the Greater Than vs. Less Than symbol in the second to last line.  This query should have had < but it had >.

**Comment by gibsonjc** [comment]
@patrickzurek - I did some more testing on the datatables errors with these queries.  I get an error trying to view the Results of any query of these eight new reports (old reports work ok) that returns more than 0.  (The report completes successfully and I can download the CSV results fine.)  Here are some where the error occurs:

KNXdb on devel:
Bib record 035 lacks OCoLC prefix - 1
Individual bibs with more than one OCLC number - 166
Bib record 035 $a lacks ocm or ocn prefix - 182
Bib record 035 begins OCoLCocn but less than 9 digits -1 
Bib record 035 $a begins OCoLCocm but has more than 8 digits - 5

DPUdb on devel:
Bib record 035 $a begins OCoLCocm but has more than 8 digits - 8
Bib record 035 $a begins OCoLCocm but lacks leading zeroes - 1
Bib record 035 $a lacks ocm or ocn prefix - 104
Individual bibs with more than one OCLC number - 69

**Comment by gibsonjc** [comment]
The one report that I mentioned that is NOT returning the same results as in Access is:
"Bib record 035 begins OCoLCocn but less than 9 digits"

In KNXdb on devel I get one result:
BIB_ID  TITLE_BRIEF OCLCNumDigits   DISPLAY_HEADING NORMAL_HEADING  SUPPRESS_IN_OPAC    CREATE_DATE
229891  Du¿¿sseldorf School of photography /  0   (OCoLC)ocn  OCOLC CN    N   4/25/2011 10:34:21 AM

In KNXdb on web-reports I get one result, but it is different from above AND it doesn't match the criteria because it starts ocm, not ocn:
BIB_ID  TITLE_BRIEF OCLCNumDigits   DISPLAY_HEADING NORMAL_HEADING  SUPPRESS_IN_OPAC    CREATE_DATE
197260  Cat in the hat comes back!  10  (OCoLC)ocm//04854956    OCOLC 048549    N   May. 24, 2007, 12:00 AM

So it is both returning a result it shouldn't and not finding the result it should.  :)

**Comment by csaundrs** [comment]
I just thought 'Cat in the hat' sounded more exciting than German photography 
ba-dum-bum

I will check it out

**Comment by gibsonjc** [comment]
Changing Title of this Issue, #92, from:
Newly Entered BIB Reports

To:
Report "Bib record 035 begins OCoLCocn but less than 9 digits" returns different results

to better reflect the one report left from this batch that needs work.  
(All the others have been pushed to prod already.)

**Comment by csaundrs** [comment]
Is this the result that comes through when running the MSAccess version of "Bib record 035 begins OCoLCocn but less than 9 digits" (for KNX)?  :


    211879
Blackwell companion to social movements /
           10
(OCoLC)ocn2003020377
OCOLC 200302037
N 19-JUN-08

    228897
Strangers in the city : reconfigurations of space, power, and social networks wi
thin China's floating population /
           10
(OCoLC)ocn2001020611
OCOLC 200102061
N 15-FEB-11


2 rows selected.

**Comment by gibsonjc** [comment]
No, the single result from KNXdb on devel when "Bib record 035 begins OCoLCocn but less than 9 digits" is run in MSAccess is still:

BIB_ID:  229891
TITLE_BRIEF: DuÌˆsseldorf School of photography / 
OCLCNumDigits: 0
DISPLAY_HEADING: (OCoLC)ocn
NORMAL_HEADING: OCOLC CN
SUPPRESS_IN_OPAC: N
CREATE_DATE: 4/25/2011 10:34:21 AM

This result is here because the prefix in the record is (OCoLC)ocn but there are no digits after the "ocn", so it has 0 which is less than 9.

The two records that you have found below actually do have problems with their OCLC numbers, but they aren't *this* problem (where ocn is present but there are Less Than 9 digits).   I don't actually think we have a query for the problem that you have found (where ocn is present but there are MORE THAN 9 digits).  Is the Greater Than/Less Than sign with the 9 just the wrong one in the SQL?


> Is this the result that comes through when running the MSAccess version of "Bib record 035 begins OCoLCocn but less than 9 digits" (for KNX)? :
211879
Blackwell companion to social movements /
10
(OCoLC)ocn2003020377
OCOLC 200302037
N 19-JUN-08
>
> 228897
Strangers in the city : reconfigurations of space, power, and social networks wi
thin China's floating population /
10
(OCoLC)ocn2001020611
OCOLC 200102061
N 15-FEB-11

**Comment by csaundrs** [comment]
Ok... I think I finally got this one straightened out.  Please double check it in devel and push to prod if it tests with expected results.

The ones that it found with a number of digits Greater than 9 might need a new report?  That would be pretty easy to do....

**Comment by gibsonjc** [comment]
Checked this with three databases in devel and the results match. Ready for Prod.

**Comment by patrickzurek** [comment]
I moved this to production just before our meeting and the output for UIU seems a little strange.  Devel returns 75 rows, production returns 74.  Is this to be expected?  

A diff of the csv output shows that the output is identical except for this row:

> 6382594,Extraits de café : flâneries en cafés montréalais : récit / ,1,(OCoLC)ocn5,OCOLC 5N5,N,2010-10-25 08:53:36+00:00

**Comment by gibsonjc** [comment]
Yep, that's correct!  They've actually fixed this one problem record (thanks for the specifics, that made checking easy!) in production that is still wrong in the data on devel.
