### ISSUE TITLE
Left hand sidebar does not scroll when content extends below browser window

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#95]
When the content in the pop-open left hand side bar extends below the height of the browser window, the browser does not introduce a vertical scroll bar allowing the user to access the reports and sub-categories hidden from view.  As more reports are entered into the system the problem will only become more obvious.  One possible solution suggested by Ed is to switch from using dynamically sized css element widths to dynamically introducing/removing & modifying bootstrap columns.   I will explore this suggestion first.

**Comment by patrickzurek** [comment]
Well, this (hopefully) actually turned out to be really easy to fix!  I was thinking too much into the problem before I even took a close look at the code I had already written.  By simply changing the css 'overflow' property for the sidebar to 'auto', it now introduces a vertical scrollbar in the sidebar (not the entire window) when the content in the sidebar exceeds the height of the browser window.

I did some testing and it seems like it's working ok.  I also tested when the content in the main section was long enough to introduce a vertical scrollbar on the right most side of the browser and there did not seem to be any interference between the two.

Please take a look on devel and let me know what you think.  An easy way to generate enough sidebar content to fill a browser's height is to search for something really generic like 'bib'

**Comment by gibsonjc** [comment]
This looks great and is working great.  I tested in FF and Chrome both mac and windows, and Safari.  I agree that the two vertical scroll bars work independently and correctly in everything I tried.  This is ready for prod.

**Comment by patrickzurek** [comment]
It's on prod now.
